### ISSUE TITLE
slowmode bot closes right away

### ISSUE THREAD

**Issue by im-in-github** [jfoster/discord-set-slowmode-bot#4]
so I followed all the instructions in the readme, and when I tried to run the bot, it still closed, and it closes fast enough that i couldnt read any kind of error message. (for windows 64 and 32 bit)

**Comment by jfoster** [comment]
Make sure you're launching the bot through cmd or powershell.
The behaviour you're describing is usually is what happens when you launch a command line application from windows explorer.
(A handy shortcut to remember; From within a desired folder press Shift+Right Click -> "Open PowerShell window here" for Win10 or "Open command window here" for Win7/8).

**Comment by jfoster** [comment]
No correspondence from author within 7 days. Closing.
@im-in-github If you're still encountering this issue please provide more details and I'll reopen.
